---
spring:
  application:
    name: "java-xah"
app:
  domain: "201.132.x.x" #改为你的公网ip
  port: "20915" #你的端口
  uuid: "2584b733-9095-4bec-a7d5-62b473540f60" #改为随机uuid
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: "api.trycloudflare.com"
  argo-token: ""
  reality-public-key: "DGE48KSEIHwvq5D83HadDINrM0sPbpN2jwLIXdv0dVI"
  reality-private-key: "MLTsKflk7IwUXaUc1Qn9OXX2W0UhhRvQ76UgimQcFmA"
  reality-short-id: "fbbe40e1"
  remarks-prefix: "vevc"
